function config($stateProvider,$urlRouterProvider){

    $stateProvider
                .state('dashboard',{
                    url:'/dashboard',
                    controller:'DashboardController',
                    templateUrl:'../../views/dashboard.html'
                })
                .state('mapa',{
                    url:'/estado',
                    templateUrl:'../../views/mapa/mapa.html',
                    controller:'MapaController'
                })
                .state('atendimentos',{
                    abstract:true,
                    url:'/atendimentos',
                    controller:'AtendimentosController',
                    templateUrl:'../../views/includes/common.html'
                })
                .state('atendimentos.listagem',{
                    url:'/listagem',
                    templateUrl:'../../views/atendimentos/atendimento-listagem.html'
                })
                .state('atendimentos.tipos',{
	                url:'/tipos',
                    templateUrl:'../../views/atendimentos/tipo-atendimento-listagem.html'
                })
                .state('relatorios',{
                    abstract:true,
                    url:'/relatorios',
                    templateUrl:'../../views/includes/common.html'
                })
                .state('relatorios.atendimentos',{
                    url:'/atendimentos',
                    templateUrl:'../../views/relatorios/atendimentos.html'
                })
                .state('relatorios.jornada',{
                    url:'/jornada',
                    templateUrl:'../../views/relatorios/jornada.html'
                })
                .state('relatorios.localizacoes',{
                    url:'/localizacoes',
                    templateUrl:'../../views/relatorios/localizacoes.html'
                })
                .state('colaboradores',{
                    abstract:true,
                    url:'/colaboradores',
                    templateUrl:'../../views/includes/common.html'
                })
                .state('colaboradores.listagem',{
                    url:'/listagem',
                    controller:'ColaboradoresController',
                    templateUrl:'../../views/colaboradores/listagem.html'
                })
                .state('colaboradores.novo',{
                    url:'/novo',
                    controller:'ColaboradoresController',
                    templateUrl:'../../views/colaboradores/form.html'
                })
                .state('colaboradores.editar',{
                    url:'/editar',
                    controller:'ColaboradoresController',
                    templateUrl:'../../views/colaboradores/form.html'
                })
                .state('colaboradores.visualizar',{
                    url:'/visualizar',
                    controller:'ColaboradoresController',
                    templateUrl:'../../views/colaboradores/form.html'
                })
                .state('colaboradores.jornada',{
                    url:'/jornada',
                    templateUrl:'../../views/colaboradores/jornada.html'
                })
                .state('locais',{
                    abstract:true,
                    url:'/locais',
                    templateUrl:'../../views/includes/common.html'
                })
                .state('locais.listagem',{
                    url:'/listagem',
                    templateUrl:'../../views/locais/locais-listagem.html'
                })
                .state('locais.tipos',{
                    url:'/tipos',
                    templateUrl:'../../views/locais/tipos-locais-listagem.html'      
                })
                .state('configuracoes',{
                    abstract:true,
                    url:'/configuracoes',
                    templateUrl:'../../views/includes/common.html'
                })
                .state('configuracoes.companhias',{
                    url:'/companhias',
                    templateUrl:'../../views/configuracoes/companhias-listagem.html'
                })
                .state('configuracoes.usuarios',{
                    url:'/usuarios',
                    templateUrl:'../../views/configuracoes/usuarios-listagem.html'
                });
                
    $urlRouterProvider.otherwise('/dashboard');
}

angular.module('desafioaurorati')
        .config(config)
        .run(function($rootScope,$state){
            console.log('aplicação rodando');
            $rootScope.state = $state;
        });

